[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "php83Extensions.pdo_pgsql", "php83Extensions.pgsql"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "mkdir -p config/jwt",
    "openssl genrsa -out config/jwt/private.pem 4096",
    "openssl rsa -in config/jwt/private.pem -pubout -out config/jwt/public.pem",
    "php bin/console cache:clear --env=prod",
    "php bin/console doctrine:migrations:migrate --no-interaction --env=prod"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"