<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260901094459 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE trainee (id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, organization_id VARCHAR(255) NOT NULL, institution VARCHAR(255) DEFAULT NULL, birth_date VARCHAR(255) DEFAULT NULL, amu_statut VARCHAR(255) DEFAULT NULL, bap VARCHAR(255) DEFAULT NULL, corps VARCHAR(255) DEFAULT NULL, category VARCHAR(255) DEFAULT NULL, campus VARCHAR(20) DEFAULT NULL, first_name_sup VARCHAR(255) DEFAULT NULL, last_name_sup VARCHAR(255) DEFAULT NULL, email_sup VARCHAR(255) DEFAULT NULL, first_name_corr VARCHAR(255) DEFAULT NULL, last_name_corr VARCHAR(255) DEFAULT NULL, email_corr VARCHAR(255) DEFAULT NULL, fonction VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE trainee');
    }
}
