<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260901102645 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE inscription (id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY, organization_id VARCHAR(255) NOT NULL, inscription_status VARCHAR(255) NOT NULL, presence_status VARCHAR(255) DEFAULT NULL, motivation TEXT DEFAULT NULL, message TEXT DEFAULT NULL, refuse TEXT DEFAULT NULL, dif BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, trainee_id INT NOT NULL, session_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5E90F6D636C682D0 ON inscription (trainee_id)');
        $this->addSql('CREATE INDEX IDX_5E90F6D6613FECDF ON inscription (session_id)');
        $this->addSql('CREATE UNIQUE INDEX traineesession_idx ON inscription (trainee_id, session_id)');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT FK_5E90F6D636C682D0 FOREIGN KEY (trainee_id) REFERENCES trainee (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT FK_5E90F6D6613FECDF FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE inscription');
    }
}
